### ISSUE TITLE
Dark mode theme

### ISSUE THREAD

**Issue by cxplay** [TsukemonoGit/nake#6]
The current float panel seems to have some issues in dark color mode?
![image](https://github.com/TsukemonoGit/nake/assets/62034099/658b49da-807a-4d2f-9a7a-a009bdf3f886)

**Comment by TsukemonoGit** [comment]
Oh, sorry.
What browser are you using?

**Comment by cxplay** [comment]
> Oh, sorry. What browser are you using?

125.0.6422.76 (Official Build, ungoogled-chromium) x64

**Comment by TsukemonoGit** [comment]
Thank you for reporting the issue. We have addressed it in version 0.1.10. The update should be reflected in the store within 1-2 days.

**Comment by cxplay** [comment]
Humm, it still looks weird.
![image](https://github.com/TsukemonoGit/nake/assets/62034099/2eb53964-4de6-44e3-9139-ae0b85f4b0d5)

**Comment by TsukemonoGit** [comment]
Oh... Which client do you use?

**Comment by cxplay** [comment]
> Oh... Which client do you use?

v0.1.10

**Comment by TsukemonoGit** [comment]
Sorry for my poor English. Which site do you use NAKE?

**Comment by cxplay** [comment]
> Sorry for my poor English. Which site do you use NAKE?

njump.me

**Comment by TsukemonoGit** [comment]
I could not reproduce it in my environment, but I made some modifications.　v0.1.11  How is it?

**Comment by cxplay** [comment]
Basic readability is back to normal, but there are still some minor problems.
![image](https://github.com/TsukemonoGit/nake/assets/62034099/fb35cff6-0c1a-43eb-9308-a6ab749eb3f8)

**Comment by TsukemonoGit** [comment]
How about the fix in v0.1.12?

**Comment by cxplay** [comment]
v0.1.12, looks good!
![image](https://github.com/TsukemonoGit/nake/assets/62034099/5de85b77-fa67-42ee-b1f6-2eda1e3b515b)

**Comment by TsukemonoGit** [comment]
thank you!!!
